### ISSUE TITLE
Weird wrapping issue

### ISSUE THREAD

**Issue by Diogenes31** [Voluntarynet/voluntary.app#18]
![image](https://user-images.githubusercontent.com/49450250/56592949-75f9f900-65a0-11e9-842c-0df1fbf1c631.png)
I noticed the client was significantly different, so I decided to check it out, and when I typed in enough stuff, the colored bar started to move over rather than the text wrapping or overflowing or something. Not sure if this is the right way to do this, but I figured you'd want to know.

**Comment by stevedekorte** [comment]
That "MyLists" UI is a different app (using the same UI frameworks) that I'm experimenting with - I just forgot to switch it back to the Peer app before pushing my commit. Good catch on the overflow. I'll take a look.

**Comment by Diogenes31** [comment]
![image](https://user-images.githubusercontent.com/49450250/56605498-2aa01480-65b9-11e9-96bd-0976736e91f8.png)
Perhaps I'm doing something wrong, but it seems to still be overflowing. I reloaded the page a couple times, and then tried opening it in a new tab, but I seem to have the same issue as before.

**Comment by stevedekorte** [comment]
I'm seeing that too. I think github hasn't updated the site yet. It takes an unpredictable amount of time between a commit and github updating it's copy of the website.

**Comment by Diogenes31** [comment]
Ah, ok. Well, I'll give it a day or so and we'll see what's up then I guess.

**Comment by stevedekorte** [comment]
I don't think it should take more than an hour.

**Comment by stevedekorte** [comment]
You can also pull from the repo and try it locally.

**Comment by stevedekorte** [comment]
Oh, I forgot to build the index file for the push :)

**Comment by Diogenes31** [comment]
That'll do it.

**Comment by stevedekorte** [comment]
pushed a fix for index
